[package]
name = "dip_hw_1"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image={ version = "0.24.0" }
show-image={ version = "0.10.1"}

